// Types
export interface Section {
  id: string
  title: string
  icon: string
}

export interface Source {
  name: string
  riskLevel: 'Low' | 'Moderate' | 'High' | 'Very High'
  coLevel: string
  description: string
}

export interface SymptomLevel {
  level: string
  cohbRange: string
  symptoms: string[]
  severity: number
  color: string
}

export interface MythItem {
  myth: string
  evidence: string
  verdict: 'Established' | 'Possible' | 'Unsupported' | 'Myth'
  details: string
}

export interface CaseStudy {
  title: string
  year: string
  location: string
  summary: string
  symptoms: string[]
  outcome: string
  source: string
}

export interface GlossaryItem {
  term: string
  definition: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface BodyEffect {
  organ: string
  icon: string
  effects: string[]
  severity: 'Mild' | 'Moderate' | 'Severe' | 'Critical'
}

export interface PreventionTip {
  category: string
  icon: string
  tips: string[]
}

export interface Reference {
  id: number
  authors: string
  title: string
  journal: string
  year: string
  url?: string
}

export const sections: Section[] = [
  { id: "introduction", title: "Introduction", icon: "BookOpen" },
  { id: "sources", title: "Sources of CO", icon: "Factory" },
  { id: "chemistry", title: "Chemistry & Physiology", icon: "FlaskConical" },
  { id: "body-effects", title: "Effects on the Body", icon: "HeartPulse" },
  { id: "symptoms", title: "Symptoms by Level", icon: "Thermometer" },
  { id: "acute-chronic", title: "Acute vs Chronic", icon: "GitCompare" },
  { id: "sleep", title: "Sleep Effects", icon: "Moon" },
  { id: "dreams", title: "Dreams & Perception", icon: "Eye" },
  { id: "psychology", title: "Psychology & Neurology", icon: "Brain" },
  { id: "long-term", title: "Long-Term Effects", icon: "Clock" },
  { id: "diagnosis", title: "Diagnosis", icon: "Stethoscope" },
  { id: "treatment", title: "Treatment", icon: "Syringe" },
  { id: "prevention", title: "Prevention", icon: "Shield" },
  { id: "myths", title: "Myths vs Evidence", icon: "Scale" },
  { id: "cases", title: "Case Studies", icon: "FileText" },
  { id: "references", title: "References", icon: "BookMarked" },
  { id: "glossary-faq", title: "Glossary & FAQ", icon: "HelpCircle" },
]

export const sources: Source[] = [
  { name: "Motor Vehicles", riskLevel: "High", coLevel: "100–7,000+ ppm", description: "Internal combustion engines produce CO as a byproduct of incomplete fuel combustion. Idling vehicles in enclosed spaces pose the greatest risk, with exhaust concentrations reaching 7,000 ppm or higher. Attached garages can allow CO to infiltrate living spaces even when the garage door is open." },
  { name: "Gas Stoves & Ovens", riskLevel: "Moderate", coLevel: "5–30 ppm (normal), up to 100+ ppm (malfunctioning)", description: "Gas ranges and ovens produce CO during combustion. Well-maintained appliances typically produce low levels, but poorly adjusted burners, clogged ports, or using a gas oven for heating can produce dangerous concentrations. The EPA estimates gas stoves contribute significantly to indoor CO levels." },
  { name: "Furnaces & Boilers", riskLevel: "High", coLevel: "50–1,500+ ppm", description: "Heating systems are one of the most common sources of CO poisoning. Cracked heat exchangers, blocked flues, or inadequate ventilation can cause CO to back up into living spaces. Annual inspections by qualified technicians are essential for safe operation." },
  { name: "Portable Generators", riskLevel: "Very High", coLevel: "500–10,000+ ppm", description: "Portable generators are among the most dangerous CO sources. A single generator can produce as much CO as hundreds of cars. The CDC reports that generator-related CO poisoning causes approximately 81 deaths annually in the US alone. Never operate a generator indoors or in partially enclosed spaces." },
  { name: "Fireplaces & Wood Stoves", riskLevel: "Moderate", coLevel: "30–200+ ppm", description: "Wood-burning appliances produce CO as part of the combustion process. Blocked chimneys, closed dampers, or creosote buildup can force CO back into the home. Regular chimney cleaning and proper damper operation are critical safety measures." },
  { name: "Water Heaters", riskLevel: "Moderate", coLevel: "10–100 ppm", description: "Gas water heaters produce CO during combustion. Malfunctioning units with dirty burners, inadequate air supply, or venting problems can produce elevated CO levels. Tankless water heaters generally produce less CO than traditional storage tank models." },
  { name: "Cigarette Smoke", riskLevel: "Low", coLevel: "10–30 ppm in enclosed spaces", description: "Cigarette smoke contains significant CO levels, typically 10,000–40,000 ppm in the smoke itself. Regular smokers maintain COHb levels of 3–10%, compared to 1-3% in non-smokers. Secondhand smoke exposure also contributes to elevated COHb in non-smokers." },
  { name: "Industrial Machinery", riskLevel: "High", coLevel: "100–5,000+ ppm", description: "Industrial equipment including forklifts, compressors, power washers, and cutting tools powered by internal combustion engines produce substantial CO. Workers in warehouses, factories, and construction sites are at particular risk, especially in poorly ventilated areas." },
  { name: "Fire & Smoke", riskLevel: "Very High", coLevel: "1,000–10,000+ ppm", description: "Structure fires produce massive amounts of CO. Firefighters and victims are at extreme risk. Even after a fire is extinguished, smoldering materials continue to produce CO. Smoke inhalation, not burns, is the leading cause of death in fires, with CO being the primary toxic agent." },
  { name: "Charcoal Grills", riskLevel: "High", coLevel: "200–5,000+ ppm", description: "Burning charcoal produces significant CO. Using charcoal grills indoors, in garages, or in tents has caused numerous deaths. Charcoal continues to produce CO even after the coals appear to be extinguished and no longer glow red." },
  { name: "Attached Garages", riskLevel: "Moderate", coLevel: "Variable", description: "Attached garages serve as a conduit for CO from vehicles into the living space. Even brief vehicle warm-ups can introduce CO into the home. Studies show that opening the garage door does not eliminate this risk. A sealed door between the garage and living space is essential." },
  { name: "Improper Ventilation", riskLevel: "High", coLevel: "Variable", description: "Any fuel-burning appliance can become dangerous if ventilation is inadequate. Blocked chimneys, closed flues, or airtight home construction (energy-efficient sealing) can trap CO inside. Negative air pressure from exhaust fans can reverse chimney drafts, pulling combustion gases back indoors." },
  { name: "Camping Equipment", riskLevel: "High", coLevel: "200–5,000+ ppm", description: "Camp stoves, lanterns, and heaters designed for outdoor use produce dangerous CO levels when used inside tents, RVs, or cabins. The CDC has documented multiple fatalities from camp stove use in enclosed spaces during camping trips." },
  { name: "Hookah / Shisha", riskLevel: "Moderate", coLevel: "300–500 ppm in exhaled air", description: "Hookah smoking generates substantial CO due to the charcoal used to heat the tobacco. One hookah session can raise COHb levels to 10-20%, causing headaches, dizziness, and nausea. The water in the hookah does not filter out CO." },
  { name: "Workplace Exposure", riskLevel: "High", coLevel: "Variable", description: "Occupational CO exposure occurs in steel mills, foundries, pulp mills, auto repair shops, and any environment with combustion engines or processes. OSHA limits workplace CO exposure to 50 ppm over an 8-hour period. Workers in confined spaces face the highest risk." },
  { name: "Paint & Solvent Fumes", riskLevel: "Low", coLevel: "Trace amounts", description: "Some chemical processes, particularly those involving methylene chloride (dichloromethane), can produce CO when metabolized by the body. Methylene chloride is found in some paint strippers, degreasers, and industrial solvents, and is metabolized to CO by the liver." },
  { name: "Boats & Marine Engines", riskLevel: "High", coLevel: "100–10,000+ ppm", description: "Marine engines, particularly stern-drive and inboard engines, can produce lethal CO concentrations. Boat cabins and enclosed areas near the stern can accumulate CO. 'Teak surfing' (holding onto the swim platform while the boat moves) has caused multiple deaths from CO poisoning." },
]

export const symptomLevels: SymptomLevel[] = [
  { level: "Very Low Exposure", cohbRange: "0–10% COHb (0–35 ppm)", symptoms: ["No noticeable symptoms in healthy adults", "Possible subtle cognitive effects at the upper end", "Reduced exercise capacity in sensitive individuals", "Fetal effects may begin at maternal levels as low as 2-3% COHb"], severity: 1, color: "hsl(142, 71%, 45%)" },
  { level: "Low Exposure", cohbRange: "10–20% COHb (35–100 ppm)", symptoms: ["Mild headache", "Slight fatigue and lethargy", "Dizziness or lightheadedness", "Shortness of breath on exertion", "Flushing of the skin", "Nausea in sensitive individuals"], severity: 2, color: "hsl(48, 96%, 53%)" },
  { level: "Moderate Exposure", cohbRange: "20–30% COHb (100–200 ppm)", symptoms: ["Throbbing headache", "Marked fatigue and weakness", "Dizziness and confusion", "Nausea and vomiting", "Visual disturbances", "Rapid heartbeat (tachycardia)", "Difficulty concentrating", "Chest pain in cardiac patients"], severity: 3, color: "hsl(25, 95%, 53%)" },
  { level: "High Exposure", cohbRange: "30–40% COHb (200–400 ppm)", symptoms: ["Severe headache", "Significant confusion and disorientation", "Visual hallucinations may occur", "Impaired coordination and balance", "Rapid breathing (tachypnea)", "Chest pain and cardiac arrhythmias", "Muscle weakness", "Inability to walk without assistance"], severity: 4, color: "hsl(0, 84%, 60%)" },
  { level: "Severe Poisoning", cohbRange: "40–50% COHb (400–800 ppm)", symptoms: ["Loss of consciousness", "Seizures and convulsions", "Cardiac arrhythmias", "Hypotension (low blood pressure)", "Respiratory failure", "Coma", "Cheyne-Stokes breathing pattern", "Pink or cherry-red skin discoloration"], severity: 5, color: "hsl(280, 70%, 50%)" },
  { level: "Fatal Poisoning", cohbRange: "50%+ COHb (800+ ppm)", symptoms: ["Cardiac arrest", "Respiratory arrest", "Brain death", "Death typically occurs at COHb levels above 50-70%", "Risk of delayed death even after removal from exposure", "Permanent brain damage in survivors"], severity: 6, color: "hsl(0, 0%, 15%)" },
]

export const bodyEffects: BodyEffect[] = [
  { organ: "Brain", icon: "Brain", effects: ["Hypoxic injury to cerebral cortex and basal ganglia", "Delayed neurological syndrome (DNS) in 10-30% of severe cases", "Memory impairment and cognitive deficits", "Personality changes and executive dysfunction", "Parkinsonian symptoms from basal ganglia damage", "White matter demyelination visible on MRI"], severity: "Critical" },
  { organ: "Heart", icon: "Heart", effects: ["Increased myocardial oxygen demand", "Decreased oxygen delivery to cardiac tissue", "Arrhythmias including atrial fibrillation and ventricular tachycardia", "Myocardial ischemia even without coronary artery disease", "Elevated cardiac biomarkers (troponin, CK-MB)", "Increased risk of subsequent cardiovascular events for years after exposure"], severity: "Severe" },
  { organ: "Lungs", icon: "Wind", effects: ["Pulmonary edema in severe cases", "ARDS (Acute Respiratory Distress Syndrome) with smoke inhalation", "Secondary pneumonia from aspiration during unconsciousness", "Chronic respiratory symptoms after severe exposure", "Increased airway reactivity"], severity: "Moderate" },
  { organ: "Blood", icon: "Droplets", effects: ["Carboxyhemoglobin (COHb) formation — CO binds hemoglobin 200-250x more tightly than oxygen", "Left-shift of the oxyhemoglobin dissociation curve", "Reduced oxygen-carrying capacity of blood", "Impaired oxygen release to tissues", "Increased 2,3-DPG production as compensatory mechanism", "Normocytic anemia in chronic exposure"], severity: "Severe" },
  { organ: "Muscles", icon: "Dumbbell", effects: ["Rhabdomyolysis in severe cases", "Muscle weakness and fatigue", "Elevated creatine kinase (CK) levels", "Myoglobinuria from muscle breakdown", "Delayed onset muscle symptoms"], severity: "Moderate" },
  { organ: "Eyes", icon: "Eye", effects: ["Visual disturbances and blurred vision", "Retinal hemorrhages in severe poisoning", "Papilledema from cerebral edema", "Visual field defects (homonymous hemianopsia)", "Cortical blindness in severe cases", "Photophobia and light sensitivity"], severity: "Moderate" },
  { organ: "Nervous System", icon: "Activity", effects: ["Peripheral neuropathy", "Autonomic dysfunction", "Sensorimotor deficits", "Ataxia and gait disturbances", "Hearing loss (sensorineural)", "Taste and smell disturbances"], severity: "Severe" },
  { organ: "Kidneys", icon: "Bean", effects: ["Acute kidney injury from rhabdomyolysis", "Myoglobin-induced renal tubular damage", "Fluid and electrolyte imbalances", "Usually reversible with treatment", "Rarely causes chronic kidney disease"], severity: "Moderate" },
  { organ: "Liver", icon: "Triangle", effects: ["Mild transaminase elevation", "Hepatic hypoxia in severe cases", "Rarely significant liver damage in isolation", "More commonly affected with co-ingestion of other toxins"], severity: "Mild" },
  { organ: "Pregnancy & Fetal", icon: "Baby", effects: ["CO crosses placenta freely — fetal COHb levels exceed maternal levels", "Fetal hemoglobin has higher affinity for CO than adult hemoglobin", "Increased risk of fetal death, stillbirth, and miscarriage", "Developmental delays and neurological impairment in survivors", "Low birth weight and preterm delivery", "No safe threshold for CO exposure during pregnancy has been established"], severity: "Critical" },
  { organ: "Children", icon: "Child", effects: ["Higher metabolic rate increases CO absorption rate", "Symptoms may present differently than in adults", "Greater risk of long-term neurological damage", "More susceptible to cardiac complications", "May not be able to communicate symptoms effectively", "Develop symptoms at lower COHb levels than adults"], severity: "Severe" },
  { organ: "Elderly", icon: "User", effects: ["Pre-existing conditions amplify CO toxicity", "Cardiovascular and respiratory comorbidities increase mortality risk", "Atypical presentation may delay diagnosis", "Reduced physiological reserve impairs recovery", "Higher mortality rates compared to younger patients", "Cognitive decline may mask CO-related symptoms"], severity: "Severe" },
]

export const myths: MythItem[] = [
  { myth: "CO poisoning can cause ghost sightings", evidence: "Established: CO-induced hallucinations, visual disturbances, and altered perception can create experiences that individuals interpret as supernatural. The neurological effects of CO on the visual cortex and temporal lobe can produce convincing sensory experiences.", verdict: "Established", details: "Multiple documented cases exist where CO poisoning was identified as the cause of reported 'hauntings.' CO affects the brain's visual processing and temporal lobe, producing hallucinations, feelings of dread, and altered perception that closely match descriptions of paranormal encounters." },
  { myth: "Haunted houses are caused by CO leaks", evidence: "Possible: While CO can produce haunting-like symptoms (hallucinations, dread, confusion), most reported haunted house experiences are not caused by CO. CO should be ruled out as a potential cause in any case involving multiple witnesses experiencing similar symptoms in an enclosed space.", verdict: "Possible", details: "The most famous case is the H family in 1921, where carbon monoxide from a faulty furnace caused the family to experience what they believed was a haunting. However, this is one mechanism among many potential explanations for such reports." },
  { myth: "Shadow people are a result of CO hallucinations", evidence: "Possible: CO can cause visual hallucinations including peripheral shadows and movement in peripheral vision. However, 'shadow people' as a specific phenomenon has multiple proposed explanations including sleep paralysis, hypnagogic hallucinations, and pareidolia.", verdict: "Possible", details: "CO-induced visual disturbances primarily affect the peripheral visual field and can create the impression of movement or shadowy figures. The temporal lobe, which processes facial recognition and body perception, is particularly sensitive to hypoxia." },
  { myth: "CO poisoning causes demonic possession", evidence: "Unsupported: The concept of demonic possession is a cultural/religious interpretation, not a medical diagnosis. While CO can cause personality changes, aggression, psychosis, and unusual behavior that might historically have been attributed to possession, there is no scientific basis for supernatural causation.", verdict: "Unsupported", details: "Historical accounts of 'possession' that may have been CO poisoning include symptoms such as seizures, personality changes, auditory and visual hallucinations, and aggressive behavior. These are well-documented neurological effects of CO exposure." },
  { myth: "Sleep paralysis is caused by CO exposure", evidence: "Unsupported: Sleep paralysis is a distinct sleep disorder related to REM sleep atonia occurring during wakefulness. While CO can disrupt sleep architecture, it does not directly cause sleep paralysis. The two conditions may coexist coincidentally.", verdict: "Unsupported", details: "Sleep paralysis involves a temporary inability to move or speak while falling asleep or waking up, often accompanied by a sense of pressure on the chest and hallucinations. CO can disrupt REM sleep and cause nightmares, but the mechanism of sleep paralysis is different." },
  { myth: "CO makes you see and hear things that aren't there", evidence: "Established: CO poisoning at moderate-to-severe levels (30%+ COHb) can cause both visual and auditory hallucinations. These are neurological symptoms resulting from cerebral hypoxia, not supernatural experiences.", verdict: "Established", details: "Visual hallucinations in CO poisoning range from simple spots and flashes to complex scenes and figures. Auditory hallucinations include buzzing, ringing, voices, and music. These are real neurological symptoms caused by oxygen deprivation to the brain." },
  { myth: "Feeling watched is a sign of CO poisoning", evidence: "Possible: CO can cause a sense of paranoia, unease, and the feeling of being observed. These symptoms result from hypoxia affecting the amygdala and other brain regions involved in threat detection and emotional processing.", verdict: "Possible", details: "The feeling of being watched or presence is associated with temporal lobe activity. CO-induced hypoxia can alter temporal lobe function, potentially producing this sensation. However, this is not a specific or reliable indicator of CO poisoning." },
  { myth: "Unexplained fear in a building means it has CO", evidence: "Unsupported: While CO can cause anxiety and feelings of dread, unexplained fear has many potential causes. CO should be considered as one possibility among many, not assumed as the default explanation.", verdict: "Unsupported", details: "CO can cause acute anxiety, panic attacks, and a general sense of dread through its effects on the amygdala and autonomic nervous system. However, attributing all unexplained fear to CO is not scientifically justified." },
  { myth: "CO causes vivid, realistic nightmares", evidence: "Possible: CO exposure disrupts normal sleep architecture and can lead to more fragmented, disturbed sleep with increased awakenings. This sleep disruption may contribute to more vivid or disturbing dream recall, though direct causation of specific nightmare content is not well-established.", verdict: "Possible", details: "Research suggests CO exposure may reduce REM sleep quality and increase sleep fragmentation. While vivid dreams and nightmares have been reported by CO poisoning survivors, the exact mechanism and prevalence require further study." },
  { myth: "All paranormal experiences can be explained by CO", evidence: "Myth: This is an overgeneralization. While CO can produce symptoms that mimic paranormal experiences in some cases, the vast majority of paranormal reports cannot be attributed to CO poisoning. CO is one of many potential explanations.", verdict: "Myth", details: "Claims that 'all hauntings are just CO leaks' are as unscientific as claims that all paranormal experiences are supernatural. The reality is more nuanced: CO is one measurable, testable explanation that should be considered alongside other factors." },
]

export const caseStudies: CaseStudy[] = [
  { title: "The H Family Haunting (1921)", year: "1921", location: "Iowa, United States", summary: "A family experienced persistent 'haunting' phenomena including strange noises, feelings of dread, and apparent apparitions over several months. A physician named Dr. W.H. Wilmer investigated and discovered a faulty furnace was producing dangerous levels of carbon monoxide. Once the furnace was repaired, all 'haunting' phenomena ceased.", symptoms: ["Headaches", "Hallucinations", "Feelings of dread", "Fatigue", "Confusion", "Visual disturbances"], outcome: "Complete resolution after furnace repair. Family recovered fully.", source: "Wilmer, W.H. (1921). 'An Illusion of the Supernatural.' Journal of Abnormal Psychology, 16(4), 236-243." },
  { title: "The Ghostly Lodger (2005)", year: "2005", location: "North Carolina, United States", summary: "A woman reported seeing a 'ghostly figure' in her apartment and experiencing overwhelming feelings of being watched. After months of frightening experiences, a maintenance check revealed a blocked furnace vent causing CO to accumulate in the apartment.", symptoms: ["Visual hallucinations", "Paranoid feelings", "Headaches", "Nausea", "Dizziness"], outcome: "Symptoms resolved after ventilation repair. No recurrence of 'paranormal' activity.", source: "Case report documented by local fire department and medical professionals." },
  { title: "School Children Mass Hallucinations (2017)", year: "2017", location: "Malaysia", summary: "Multiple students at a school reported seeing a 'dark figure' and experiencing unusual fear. Investigation revealed a malfunctioning water heater in a poorly ventilated utility room adjacent to the affected classrooms.", symptoms: ["Mass visual hallucinations", "Anxiety and panic", "Headaches", "Dizziness", "Nausea"], outcome: "All symptoms resolved after CO source was eliminated. Students recovered without long-term effects.", source: "Local health department investigation report." },
  { title: "The Hotel Poisoning (2008)", year: "2008", location: "North Carolina, United States", summary: "Guests at a hotel reported hearing strange noises, experiencing vivid nightmares, and feeling a 'presence' in their rooms. Three guests were hospitalized with non-specific symptoms before fire department testing revealed CO levels exceeding 200 ppm from a pool heater.", symptoms: ["Auditory phenomena", "Vivid nightmares", "Feelings of presence", "Headache", "Fatigue", "Nausea"], outcome: "Hotel evacuated, CO source repaired. No fatalities. Several guests received hyperbaric oxygen therapy.", source: "Local fire marshal report and CDC MMWR." },
  { title: "Submarine Crew Incidents (Historical)", year: "Various", location: "Multiple locations", summary: "Historical accounts from submarine crews describe 'apparitions,' unusual sounds, and feelings of an unseen presence. Modern analysis suggests these experiences coincided with periods of poor air quality and elevated CO levels from diesel engines and battery charging.", symptoms: ["Visual and auditory phenomena", "Cognitive impairment", "Personality changes", "Headaches", "Poor judgment"], outcome: "Improved ventilation and CO monitoring eliminated these reports.", source: "Naval medical records and historical analyses." },
  { title: "The 'Cursed' Office Building (2014)", year: "2014", location: "United Kingdom", summary: "Office workers in a converted warehouse reported a pattern of 'hauntings' — shadowy figures, unexplained sounds, and a general feeling of unease that intensified during winter months. Environmental testing revealed an aging gas heating system producing CO levels that peaked during cold weather.", symptoms: ["Peripheral visual disturbances", "Auditory phenomena", "Anxiety", "Cognitive difficulties", "Fatigue", "Headaches worsening in winter"], outcome: "Heating system replacement resolved all symptoms. Building occupancy returned to normal.", source: "Environmental health assessment report." },
]

export const glossary: GlossaryItem[] = [
  { term: "Carboxyhemoglobin (COHb)", definition: "A stable complex of carbon monoxide and hemoglobin formed when CO binds to hemoglobin in red blood cells. COHb reduces the blood's oxygen-carrying capacity because CO binds to hemoglobin approximately 200-250 times more tightly than oxygen." },
  { term: "Hyperbaric Oxygen Therapy (HBOT)", definition: "A medical treatment that involves breathing 100% oxygen in a pressurized chamber, typically at 2-3 atmospheres absolute (ATA). HBOT accelerates CO elimination by dissolving oxygen directly in plasma, bypassing hemoglobin." },
  { term: "Hypoxia", definition: "A condition in which tissues do not receive adequate oxygen supply. In CO poisoning, hypoxia occurs despite normal blood oxygen levels because CO prevents oxygen from being released to tissues (histotoxic hypoxia)." },
  { term: "Delayed Neurological Syndrome (DNS)", definition: "A condition occurring in 10-30% of severe CO poisoning cases, characterized by the reappearance of neurological symptoms 2-40 days after apparent recovery. Symptoms include cognitive impairment, personality changes, parkinsonism, and movement disorders." },
  { term: "Half-life of COHb", definition: "The time required for COHb levels to decrease by 50%. On room air, the half-life is approximately 4-6 hours. Breathing 100% oxygen at sea level reduces the half-life to approximately 60-90 minutes. HBOT at 2.5 ATA reduces it to approximately 20-30 minutes." },
  { term: "Oxyhemoglobin Dissociation Curve", definition: "A curve that describes the relationship between the partial pressure of oxygen (PaO2) and the saturation of hemoglobin with oxygen (SaO2). CO exposure shifts this curve to the left, impairing oxygen release to tissues." },
  { term: "Cerebral Hypoxia", definition: "Insufficient oxygen supply to the brain. The brain is particularly vulnerable to CO-induced hypoxia due to its high metabolic rate and limited anaerobic capacity. Even brief periods of cerebral hypoxia can cause irreversible damage." },
  { term: "Pulse Oximetry", definition: "A non-invasive method for measuring oxygen saturation. Standard pulse oximeters cannot distinguish between oxyhemoglobin and carboxyhemoglobin, potentially giving falsely normal readings in CO poisoning. CO-oximetry is required for accurate measurement." },
  { term: "CO-oximetry", definition: "A specialized form of spectrophotometry that can distinguish between oxyhemoglobin, carboxyhemoglobin, methemoglobin, and deoxyhemoglobin. This is the required method for accurate COHb measurement." },
  { term: "Mitochondrial Dysfunction", definition: "Impairment of mitochondrial function, particularly the electron transport chain, due to CO binding to cytochrome c oxidase (Complex IV). This disrupts cellular respiration and ATP production even after COHb levels have normalized." },
  { term: "Oxidative Stress", definition: "An imbalance between the production of reactive oxygen species (ROS) and the body's antioxidant defenses. CO poisoning triggers oxidative stress through mitochondrial dysfunction, inflammation, and reperfusion injury during treatment." },
  { term: "Basal Ganglia", definition: "Deep brain structures including the globus pallidus and putamen that are particularly vulnerable to CO-induced damage. Lesions in the globus pallidus are a hallmark radiological finding in severe CO poisoning." },
  { term: "Arterial Blood Gas (ABG)", definition: "A blood test measuring oxygen and carbon dioxide levels, pH, and bicarbonate in arterial blood. In CO poisoning, ABG may show normal or elevated PaO2 despite tissue hypoxia, making it an unreliable indicator of CO severity." },
  { term: "Reperfusion Injury", definition: "Tissue damage that occurs when blood supply (and oxygen) returns to tissues after a period of hypoxia. In CO poisoning, treatment-induced reperfusion can paradoxically increase oxidative damage through the generation of reactive oxygen species." },
  { term: "Normocapnia", definition: "Normal levels of carbon dioxide in the blood. Unlike many forms of respiratory failure, CO poisoning typically does not cause elevated CO2 levels, which can make diagnosis more challenging." },
]

export const faqItems: FAQItem[] = [
  { question: "What is carbon monoxide?", answer: "Carbon monoxide (CO) is a colorless, odorless, tasteless, and non-irritating gas produced by the incomplete combustion of carbon-containing fuels. It is composed of one carbon atom and one oxygen atom (chemical formula: CO). These physical properties make it impossible for humans to detect without specialized equipment, earning it the name 'the silent killer.'" },
  { question: "How does carbon monoxide poisoning occur?", answer: "CO poisoning occurs when CO is inhaled and binds to hemoglobin in red blood cells, forming carboxyhemoglobin (COHb). Because CO binds to hemoglobin 200-250 times more tightly than oxygen, it displaces oxygen from the blood, causing tissue hypoxia. CO also binds to myoglobin and cytochrome oxidase, disrupting cellular respiration even at the mitochondrial level." },
  { question: "Can I smell or see carbon monoxide?", answer: "No. Carbon monoxide is completely invisible, odorless, and tasteless. You cannot detect it with any of your senses. This is why CO detectors are essential — they are the only reliable way to detect dangerous CO levels in your environment. Some people mistakenly believe they can smell CO, but they are likely smelling other combustion byproducts." },
  { question: "How quickly can CO poisoning be fatal?", answer: "At concentrations of 1,286 ppm (0.13%), CO can be fatal within 1-3 minutes. At 400 ppm, death can occur within 1-2 hours. At 100 ppm, symptoms develop gradually over several hours. The speed of poisoning depends on the CO concentration, duration of exposure, individual health status, and activity level (exercising increases inhalation rate)." },
  { question: "Are children more vulnerable to CO poisoning?", answer: "Yes. Children have higher metabolic rates, which means they absorb CO faster relative to their body size. They also have smaller blood volumes, so COHb levels rise more quickly. Children may present with atypical symptoms or be unable to communicate their symptoms effectively, leading to delayed diagnosis and treatment." },
  { question: "What should I do if I suspect CO poisoning?", answer: "Immediately move to fresh air and call emergency services (911 or your local emergency number). Do not re-enter the building until it has been inspected by professionals. If anyone is unconscious, do not attempt rescue without proper equipment — call for professional help. Seek medical evaluation even if symptoms resolve, as delayed complications can occur." },
  { question: "Do CO detectors really work?", answer: "Yes. UL-listed CO detectors are proven life-saving devices that sound an alarm when CO levels reach dangerous thresholds. The CDC recommends installing CO detectors on every level of your home and near sleeping areas. Test detectors monthly and replace batteries annually. Replace the entire unit every 5-7 years or according to manufacturer guidelines." },
  { question: "Can CO poisoning cause long-term brain damage?", answer: "Yes. In severe cases, CO poisoning can cause permanent neurological damage including memory impairment, personality changes, parkinsonism, and cognitive deficits. The condition known as Delayed Neurological Syndrome (DNS) affects 10-30% of patients with severe poisoning, with symptoms appearing 2-40 days after apparent recovery." },
  { question: "Is hyperbaric oxygen therapy always necessary?", answer: "No. HBOT is recommended for patients with severe CO poisoning (COHb > 25%, loss of consciousness, cardiac involvement, neurological symptoms, or pregnancy). Mild-to-moderate cases may be treated with normobaric 100% oxygen alone. The decision is made by the treating physician based on clinical presentation and COHb levels." },
  { question: "Can CO build up in my home from normal cooking?", answer: "Gas stoves produce small amounts of CO during normal operation, typically 5-30 ppm which is within acceptable limits. However, using a gas oven for heating, operating a stove with a yellow flame (indicating incomplete combustion), or cooking in a poorly ventilated space can cause dangerous CO buildup. Always use ventilation when cooking with gas." },
]

export const preventionTips: PreventionTip[] = [
  { category: "CO Detectors", icon: "Siren", tips: ["Install battery-backed CO detectors on every level of your home", "Place detectors near sleeping areas and within 10 feet of bedrooms", "Test detectors monthly and replace batteries at least once per year", "Replace the entire detector unit every 5-7 years per manufacturer guidelines", "Choose detectors with digital displays showing CO levels", "Interconnect detectors so all units alarm simultaneously"] },
  { category: "Home Safety", icon: "Home", tips: ["Have all fuel-burning appliances inspected annually by a qualified technician", "Never use a gas oven or range for heating", "Ensure proper ventilation for all combustion appliances", "Open flues when using fireplaces", "Never use portable flameless chemical heaters indoors", "Keep gas appliances properly adjusted and clean"] },
  { category: "Generator Safety", icon: "Zap", tips: ["NEVER operate a portable generator indoors, in garages, or near windows", "Place generators at least 20 feet from any building, doors, or windows", "Use battery-operated CO detectors when running a generator nearby", "Turn off the generator and let it cool before refueling", "Install battery backup systems as a safer alternative", "Follow all manufacturer instructions for safe operation"] },
  { category: "Vehicle Safety", icon: "Car", tips: ["Never leave a vehicle running in an attached garage, even with the door open", "Have your vehicle's exhaust system checked annually", "Never idle your vehicle in a closed garage", "Check for exhaust leaks if you smell fumes while driving", "Be aware that even open garage doors do not provide adequate ventilation", "Consider installing a CO detector in the garage"] },
  { category: "Appliance Maintenance", icon: "Wrench", tips: ["Schedule annual inspections for furnaces, water heaters, and boilers", "Clean chimneys and flues every year before heating season", "Look for yellow flames on gas appliances (blue indicates proper combustion)", "Check venting systems for blockages, corrosion, or disconnections", "Replace aging appliances — newer models have better safety features", "Never patch or tape vent pipes — replace damaged sections entirely"] },
  { category: "Ventilation", icon: "Wind", tips: ["Ensure your home has adequate air exchange — modern airtight homes need mechanical ventilation", "Do not block or seal ventilation openings for fuel-burning appliances", "Install exhaust fans in kitchens and bathrooms that vent to the outside", "Be aware that exhaust fans can create negative pressure, pulling CO back indoors", "Have a professional assess your home's ventilation if you add insulation or new windows", "Keep dryer vents and range hoods clean and unobstructed"] },
  { category: "Fire Safety", icon: "Flame", tips: ["Never use charcoal grills, hibachis, or camp stoves indoors or in tents", "Do not use gas-powered tools indoors or in enclosed spaces", "Open the damper before using a fireplace and keep it open until the fire is completely out", "Do not close the fireplace damper until the fire is completely out and coals are cold", "Never burn anything in a stove or fireplace that is not vented", "Install and maintain smoke alarms alongside CO detectors"] },
  { category: "Winter Precautions", icon: "Snowflake", tips: ["Clear snow and ice from exhaust vents, chimneys, and flues after winter storms", "Be extra cautious during power outages — do not use ovens or grills for heat", "Warm your car outside before driving, not in an attached garage", "Check that furnace intake and exhaust pipes are clear of snowdrifts", "Be aware that boarding up windows during storms can reduce ventilation", "Keep emergency heating equipment (properly vented) as backup"] },
  { category: "Travel & Camping", icon: "Tent", tips: ["Never use fuel-burning equipment inside a tent, camper, or RV", "Carry battery-operated CO detectors when camping or traveling", "Follow all RV manufacturer guidelines for appliance ventilation", "Be cautious of cabin heater fumes in boats — install marine CO detectors", "Do not sleep in a room with a running kerosene heater or gas lantern", "Know the location of the nearest medical facility when traveling"] },
]

export const references: Reference[] = [
  { id: 1, authors: "Rose JJ, Wang L, Xu Q, et al.", title: "Carbon Monoxide Poisoning: Pathogenesis, Management, and Future Directions of Therapy", journal: "American Journal of Respiratory and Critical Care Medicine", year: "2017", url: "https://doi.org/10.1164/rccm.201606-1175CI" },
  { id: 2, authors: "Weaver LK.", title: "Carbon Monoxide Poisoning", journal: "New England Journal of Medicine", year: "2009", url: "https://doi.org/10.1056/NEJMct0808871" },
  { id: 3, authors: "Centers for Disease Control and Prevention (CDC)", title: "Carbon Monoxide Poisoning — Frequently Asked Questions", journal: "CDC National Center for Environmental Health", year: "2023", url: "https://www.cdc.gov/co/faqs.htm" },
  { id: 4, authors: "World Health Organization (WHO)", title: "WHO Guidelines for Indoor Air Quality: Selected Pollutants", journal: "WHO Regional Office for Europe", year: "2010" },
  { id: 5, authors: "Hampson NB, Hauff NM", title: "Risk Factors for Short-Term Mortality from Carbon Monoxide Poisoning Treated with Hyperbaric Oxygen", journal: "Critical Care Medicine", year: "2008" },
  { id: 6, authors: "NIOSH (National Institute for Occupational Safety and Health)", title: "Carbon Monoxide in the Workplace", journal: "NIOSH Safety and Health Topic", year: "2022", url: "https://www.cdc.gov/niosh/topics/co/" },
  { id: 7, authors: "Hopkins RO, Woon FL, Weaver LK", title: "Carbon Monoxide Poisoning and Brain Injury", journal: "Neuropsychology Review", year: "2006" },
  { id: 8, authors: "Raub JA, Mathieu-Nolf M, Hampson NB, Thom SR", title: "Carbon Monoxide Poisoning — A Public Health Perspective", journal: "Toxicology", year: "2000" },
  { id: 9, authors: "Thom SR, Bhopale VM, Han D, et al.", title: "Intravascular Neutrophil Activation Due to Carbon Monoxide Poisoning", journal: "American Journal of Respiratory and Critical Care Medicine", year: "2006" },
  { id: 10, authors: "Piantadosi CA", title: "Carbon Monoxide Poisoning", journal: "New England Journal of Medicine", year: "2002" },
  { id: 11, authors: "Myers RAM, Britten JS", title: "Are Carbon Monoxide Intoxication and the 'Haunted House' Syndrome the Same?", journal: "Journal of Burn Care & Rehabilitation", year: "1992" },
  { id: 12, authors: "Hampson NB", title: "Firefighter Suicide and Carbon Monoxide Exposure", journal: "Journal of Occupational and Environmental Medicine", year: "2016" },
  { id: 13, authors: "Gale C, Henderson B, Hulme J, et al.", title: "Oxygen Treatment for Carbon Monoxide Poisoning", journal: "Cochrane Database of Systematic Reviews", year: "2020" },
  { id: 14, authors: "Weaver LK, Hopkins RO, Chan KJ, et al.", title: "Hyperbaric Oxygen for Acute Carbon Monoxide Poisoning", journal: "New England Journal of Medicine", year: "2002" },
  { id: 15, authors: "Ernst A, Zibrak JD", title: "Carbon Monoxide Poisoning", journal: "New England Journal of Medicine", year: "1998" },
  { id: 16, authors: "American Lung Association", title: "Carbon Monoxide and Health", journal: "American Lung Association Health Education", year: "2023", url: "https://www.lung.org/clean-air/at-home/indoor-air-pollutants/carbon-monoxide" },
  { id: 17, authors: "Omaye ST", title: "Metabolic Modulation of Carbon Monoxide Toxicity", journal: "Toxicology", year: "2002" },
  { id: 18, authors: "Chou KJ", title: "Carbon Monoxide Poisoning", journal: "Emergency Medicine Clinics of North America", year: "2017" },
  { id: 19, authors: "Wilmer WH", title: "An Illusion of the Supernatural", journal: "Journal of Abnormal Psychology", year: "1921" },
  { id: 20, authors: "Mott JA, Wolfe MI, Alverson CJ, et al.", title: "National Vehicle Emissions Policies and Practices and Declining US Carbon Monoxide-Related Mortality", journal: "JAMA", year: "2002" },
]

export const introContent = {
  paragraphs: [
    "Carbon monoxide (CO) is a colorless, odorless, tasteless, and non-irritating toxic gas produced by the incomplete combustion of carbon-containing fuels including natural gas, propane, gasoline, oil, wood, and coal. With the chemical formula CO, this diatomic molecule consists of one carbon atom covalently bonded to one oxygen atom, creating a compound that is deceptively simple in structure yet devastatingly dangerous in its biological effects. Carbon monoxide has a molecular weight of 28.01 g/mol, a density slightly less than that of air (0.97 times that of air at standard temperature and pressure), and is sparingly soluble in water.",
    "The insidious nature of CO lies precisely in its undetectability by human senses. Unlike many other toxic gases, CO provides no sensory warning of its presence — no smell, no taste, no irritation to the eyes or respiratory tract. This property has earned carbon monoxide the grim but accurate designation of 'the silent killer.' The gas acts as a chemical asphyxiant, meaning it produces its toxic effects by interfering with the body's ability to utilize oxygen at the cellular level, rather than by directly damaging tissues through irritation or corrosion.",
    "The history of carbon monoxide poisoning extends back centuries, with early descriptions appearing in ancient Greek and Roman texts referencing toxic fumes from burning charcoal. However, it was not until 1857 that Claude Bernard first described the mechanism of CO toxicity, demonstrating that CO displaces oxygen from hemoglobin. The industrial revolution dramatically increased CO exposure risks as coal and gas became primary energy sources. By the early 20th century, CO poisoning from gas lighting, heating, and industrial processes was recognized as a major public health concern. The development of gas detection technologies and safety regulations has significantly reduced mortality rates in developed nations, but CO poisoning remains a persistent and deadly problem worldwide.",
    "Globally, carbon monoxide poisoning is one of the most common causes of fatal poisoning, accounting for an estimated 50,000 or more emergency department visits annually in the United States alone, with approximately 400-500 deaths per year attributed to unintentional CO exposure. In many developing nations, the burden is significantly higher due to reliance on biomass fuels for cooking and heating in poorly ventilated homes. The World Health Organization estimates that indoor air pollution, including CO exposure, contributes to approximately 3.8 million premature deaths annually worldwide. These statistics underscore the critical importance of public education, prevention strategies, and prompt medical intervention in reducing the global burden of CO poisoning."
  ]
}

export const chemistryContent = {
  paragraphs: [
    "Carbon monoxide consists of a single carbon atom triple-bonded to a single oxygen atom (C≡O), with a bond length of 112.8 picometers. The molecule has a small dipole moment due to the unequal sharing of electrons, and it is isoelectronic with molecular nitrogen (N₂) and cyanide ion (CN⁻). The triple bond between carbon and oxygen is one of the strongest chemical bonds in organic chemistry, with a bond dissociation energy of approximately 1072 kJ/mol. This strong bond is one reason why CO is relatively stable in the atmosphere, with an average lifetime of approximately one to two months before being oxidized to carbon dioxide.",
    "The reason CO is colorless, odorless, and tasteless relates to its molecular properties. Color requires absorption of visible light, which CO does not do to any significant degree. Odor requires interaction with olfactory receptors, which typically involves larger, more complex molecules that can bind to receptor proteins. CO's small molecular size and non-polar character prevent it from activating these receptors. Similarly, taste perception requires interaction with taste receptor cells on the tongue, and CO does not bind to these receptors. This combination of physical properties makes CO impossible for humans to detect without specialized equipment — a fact that is central to its lethality.",
    "The primary mechanism of CO toxicity involves its interaction with hemoglobin, the oxygen-carrying protein in red blood cells. Hemoglobin contains four heme groups, each with an iron atom (Fe²⁺) at its center that normally binds oxygen. CO binds to the same iron atom but with an affinity approximately 200-250 times greater than that of oxygen. This means that even trace amounts of CO in inhaled air can result in significant carboxyhemoglobin (COHb) formation. At sea level, breathing air containing just 0.1% CO (1,000 ppm) can produce COHb levels of approximately 50% within a few hours.",
    "The binding of CO to hemoglobin produces four interrelated toxic effects. First, it reduces the oxygen-carrying capacity of blood by occupying binding sites that would normally carry oxygen. Second, it increases the affinity of the remaining heme sites for oxygen (left-shift of the oxyhemoglobin dissociation curve), impairing oxygen release to tissues. Third, CO binds to myoglobin in muscle tissue, further reducing oxygen storage and delivery. Fourth, and perhaps most significantly, CO binds to cytochrome c oxidase (Complex IV) in the mitochondrial electron transport chain, directly inhibiting cellular respiration and ATP production. This last effect persists even after COHb levels have been normalized, explaining why patients may deteriorate after apparently successful initial treatment.",
    "At the cellular level, CO-induced hypoxia triggers a cascade of damaging processes. Oxidative stress occurs when the electron transport chain is impaired, leading to the production of reactive oxygen species (ROS) including superoxide anion, hydrogen peroxide, and hydroxyl radical. These ROS damage cellular membranes, proteins, and DNA. Inflammatory responses are activated, with the release of pro-inflammatory cytokines and recruitment of immune cells to affected tissues. Neuronal injury results from the particular vulnerability of brain tissue to hypoxia — the brain consumes approximately 20% of the body's oxygen despite being only 2% of body weight, and it has minimal anaerobic capacity. The basal ganglia, particularly the globus pallidus, are especially susceptible, and bilateral globus pallidus lesions are a hallmark finding in severe CO poisoning."
  ],
  keyPoints: [
    "CO binds hemoglobin with 200-250x greater affinity than oxygen",
    "Left-shift of the oxyhemoglobin dissociation curve impairs oxygen release to tissues",
    "CO binds to cytochrome c oxidase, directly inhibiting cellular respiration",
    "The globus pallidus in the basal ganglia is particularly vulnerable to CO damage",
    "Oxidative stress and inflammation continue even after CO is eliminated from the body",
    "CO's triple bond (C≡O) makes it chemically stable and biologically persistent"
  ]
}

export const acuteChronicContent = {
  acute: [
    "Acute carbon monoxide poisoning occurs from a single exposure to high concentrations of CO over a short period, typically minutes to hours. The clinical presentation depends on the COHb level achieved, which is determined by the concentration of CO in the inhaled air, the duration of exposure, the individual's minute ventilation rate, and their baseline cardiopulmonary status. Acute poisoning presents as a spectrum ranging from mild headache and flu-like symptoms at low COHb levels to unconsciousness, seizures, and death at higher levels. The onset of symptoms can be insidious, particularly at lower concentrations, with victims often not realizing they are being poisoned until they are too disoriented to seek help.",
    "In severe acute poisoning, the patient may present with loss of consciousness, seizures, cardiac arrhythmias, hypotension, and respiratory failure. The classic physical finding of cherry-red skin color is a post-mortem finding and is rarely observed in living patients. Rhabdomyolysis and myoglobinuria may occur, leading to acute kidney injury. Cardiac complications are particularly dangerous and include myocardial ischemia, arrhythmias, and sudden cardiac death. Even patients who appear to recover fully from acute poisoning may develop delayed neurological syndrome days to weeks later."
  ],
  chronic: [
    "Chronic or repeated low-level CO exposure represents a more insidious form of poisoning that is significantly harder to diagnose. Victims may be exposed to low concentrations of CO (10-50 ppm) for days, weeks, or even months, often from a slow leak in a home heating system or chronic workplace exposure. The symptoms are typically non-specific and can mimic many other conditions including chronic fatigue syndrome, depression, influenza, and other viral illnesses.",
    "Common symptoms of chronic CO exposure include persistent or recurrent headaches (particularly morning headaches upon waking), chronic fatigue, cognitive difficulties ('brain fog'), difficulty concentrating, memory problems, mood changes including depression and irritability, dizziness, nausea, and generalized malaise. Because these symptoms are non-specific, chronic CO poisoning is frequently misdiagnosed or dismissed. The key diagnostic clue is often that symptoms improve when the patient leaves the affected environment (such as going to work or on vacation) and recur upon return. Special populations including pregnant women, children, the elderly, and individuals with pre-existing cardiovascular or respiratory disease are at heightened risk from chronic low-level exposure."
  ],
  comparisonPoints: [
    { aspect: "Exposure Pattern", acute: "Single, high-concentration event lasting minutes to hours", chronic: "Repeated or continuous low-level exposure over days to months" },
    { aspect: "COHb Levels", acute: "Often >20%, can exceed 50% in severe cases", chronic: "Typically 5-15%, rarely exceeds 20%" },
    { aspect: "Onset", acute: "Rapid, symptoms develop within minutes to hours", chronic: "Gradual, symptoms develop and worsen over days to weeks" },
    { aspect: "Diagnosis", acute: "Usually suspected based on circumstances (found near running engine, fire, etc.)", chronic: "Often missed or misdiagnosed; requires high clinical suspicion" },
    { aspect: "Common Symptoms", acute: "Headache, dizziness, nausea, confusion, loss of consciousness", chronic: "Chronic headaches, fatigue, cognitive difficulties, mood changes" },
    { aspect: "Treatment", acute: "100% oxygen, possibly HBOT; emergency response", chronic: "Remove from source, normobaric oxygen, address underlying cause" },
    { aspect: "Risk of DNS", acute: "10-30% of severe cases (COHb >25%, loss of consciousness)", chronic: "Lower but documented; neurocognitive deficits may persist" },
    { aspect: "Prognosis", acute: "Variable; full recovery to permanent disability or death", chronic: "Generally better with early identification and source elimination" },
  ]
}

export const sleepContent = {
  paragraphs: [
    "Carbon monoxide exposure has significant and well-documented effects on sleep quality and architecture. One of the most characteristic and clinically important symptoms of chronic CO poisoning is the occurrence of morning headaches upon awakening. These headaches are typically bilateral, frontal or diffuse, and improve after leaving the affected environment. Morning headaches in CO poisoning result from the cumulative effect of breathing CO-contaminated air throughout the night in a closed bedroom, often with reduced ventilation. During sleep, the metabolic rate decreases but CO continues to bind to hemoglobin, causing COHb levels to rise progressively throughout the night.",
    "Research has demonstrated that CO exposure disrupts normal sleep architecture in several ways. Studies using polysomnography have shown that CO exposure can reduce total sleep time, increase sleep onset latency (time to fall asleep), and increase the number of awakenings during the night. The distribution of sleep stages may be altered, with some studies reporting reductions in REM (rapid eye movement) sleep percentage and changes in slow-wave (deep) sleep. Sleep fragmentation — the disruption of continuous sleep into shorter, more frequent episodes — is a consistent finding. This fragmentation prevents the restorative benefits of normal sleep cycling and contributes to the excessive daytime sleepiness, fatigue, and cognitive impairment reported by patients.",
    "The relationship between CO exposure and specific sleep phenomena such as vivid dreams and nightmares is an area of ongoing research. CO-induced hypoxia affects the brain regions involved in dream generation and emotional processing, particularly the limbic system and prefrontal cortex. Some patients with CO poisoning report unusually vivid or disturbing dreams, but whether CO directly alters dream content or simply increases dream recall due to more frequent awakenings remains unclear. The existing evidence suggests that sleep disruption from CO is primarily due to physiological effects (headache, discomfort, respiratory changes) rather than direct neurochemical modulation of sleep circuits.",
    "Excessive daytime sleepiness, poor concentration, and the subjective sensation of 'brain fog' are common complaints in both acute and chronic CO poisoning. These symptoms result from the combination of sleep disruption, cerebral hypoxia, and the direct neurotoxic effects of CO on brain function. Brain fog — the subjective experience of mental cloudiness, slowed thinking, and difficulty processing information — is one of the most frequently reported and most persistent symptoms of chronic CO exposure. Importantly, these cognitive symptoms may persist for weeks or months after COHb levels have returned to normal, particularly in cases of moderate-to-severe exposure."
  ],
  keyFindings: [
    "Morning headaches are a hallmark symptom of chronic CO exposure during sleep",
    "CO exposure reduces total sleep time and increases sleep fragmentation",
    "REM sleep may be reduced in CO-exposed individuals",
    "Excessive daytime sleepiness correlates with COHb levels and sleep disruption",
    "Brain fog and cognitive impairment may persist long after CO elimination",
    "Sleep quality typically improves after CO source removal, but recovery may take weeks",
    "Insomnia has been reported in some cases, potentially related to anxiety and autonomic dysfunction"
  ]
}

export const dreamsContent = {
  established: [
    "CO poisoning at moderate-to-severe levels (COHb >30%) can cause both visual and auditory hallucinations. These are real neurological symptoms caused by cerebral hypoxia affecting the visual cortex, auditory cortex, and temporal lobes. Hallucinations may range from simple flashes of light and geometric patterns to complex visual scenes, figures, and voices. These symptoms are well-documented in the medical literature and are recognized as diagnostic indicators of significant CO exposure requiring immediate treatment.",
    "CO can cause a generalized sense of paranoia, unease, and the feeling of being watched or followed. These symptoms result from hypoxia-induced dysfunction of the amygdala and other brain regions involved in threat detection, emotional processing, and social cognition. The feeling of an unseen 'presence' has been documented in CO poisoning cases and is a recognized neurological symptom, not a supernatural phenomenon."
  ],
  possible: [
    "CO exposure may contribute to the experience of sleep paralysis-like episodes. While CO does not directly cause sleep paralysis (which is a distinct REM-sleep phenomenon), CO-induced sleep disruption, anxiety, and alterations in sleep architecture may increase the frequency or intensity of sleep paralysis episodes in susceptible individuals. The sense of a threatening presence commonly reported in sleep paralysis could theoretically be amplified by CO-related temporal lobe dysfunction.",
    "CO exposure may increase the frequency or vividness of nightmares and disturbing dreams. The mechanism is likely indirect — by disrupting normal sleep architecture and increasing the number of awakenings (particularly from REM sleep), CO exposure may increase dream recall and the subjective experience of disturbing dream content. Direct effects of CO on the limbic system and emotional processing centers could also alter the emotional tone of dreams.",
    "CO-induced visual disturbances affecting the peripheral visual field could contribute to reports of 'shadow people' or shadowy figures seen in the periphery. The visual association cortex, which processes peripheral vision and motion detection, is susceptible to hypoxia. However, this is one of multiple proposed mechanisms for such experiences and should not be considered a definitive explanation."
  ],
  unsupported: [
    "The claim that CO poisoning alone is sufficient to explain all reported 'haunted house' phenomena. While CO can produce some symptoms that overlap with reported paranormal experiences, most alleged hauntings involve multiple factors, and many have been investigated without finding evidence of CO exposure. CO should be considered as one possible contributing factor, not a universal explanation.",
    "The assertion that CO poisoning is the primary cause of reports of demonic possession throughout history. While some historical accounts of possession may have involved CO-related symptoms (seizures, personality changes, hallucinations), the concept of possession is a cultural and religious interpretation that cannot be reduced to a single medical explanation.",
    "Claims that specific paranormal phenomena such as electronic voice phenomena (EVP), moving objects, or temperature fluctuations are caused by CO. These reported phenomena are outside the known physiological effects of CO exposure."
  ],
  myths: [
    "All hauntings are caused by CO leaks — this overgeneralization is not supported by evidence. While specific documented cases exist where CO was the cause, the vast majority of reported hauntings cannot be attributed to CO poisoning.",
    "If you feel a 'presence' in your home, it must be CO — the feeling of being watched or a sense of presence has many potential explanations including anxiety, stress, sleep deprivation, infrasound, and suggestibility, in addition to possible CO exposure.",
    "CO poisoning proves the supernatural doesn't exist — this is a logical fallacy. Explaining some experiences through CO poisoning does not invalidate all unexplained phenomena. Science addresses testable claims individually, not as a group."
  ]
}

export const psychologyContent = {
  paragraphs: [
    "The neurological and psychological effects of carbon monoxide poisoning are among the most significant and long-lasting consequences of CO exposure. The brain, with its high metabolic rate and limited capacity for anaerobic metabolism, is particularly vulnerable to CO-induced hypoxia. Even moderate CO exposure can produce measurable cognitive deficits, while severe poisoning can cause profound and permanent neurological damage. The spectrum of psychological and neurological effects ranges from subtle cognitive slowing and mild memory impairment to severe dementia, psychosis, and persistent vegetative states.",
    "Memory impairment is one of the most common and clinically significant consequences of CO poisoning. Both anterograde memory (the ability to form new memories) and retrograde memory (recall of past events) can be affected. The hippocampus, a brain structure critical for memory consolidation, is particularly vulnerable to hypoxic injury. Patients frequently report difficulty remembering recent conversations, appointments, and daily tasks. In severe cases, amnesia for the poisoning event itself is common. These memory deficits may persist for months or years, and some patients never fully recover their pre-exposure memory function.",
    "Attention and concentration deficits are nearly universal in moderate-to-severe CO poisoning. Patients describe difficulty sustaining attention on tasks, easy distractibility, and a subjective sense of mental slowness or 'brain fog.' Neuropsychological testing often reveals impaired performance on tests of sustained attention, selective attention, and divided attention. Executive dysfunction — difficulty with planning, organizing, problem-solving, and decision-making — is also common and can significantly impact the patient's ability to return to work or manage daily activities independently.",
    "Mood changes are frequently observed following CO poisoning, with depression and anxiety being the most commonly reported psychiatric symptoms. The mechanism is multifactorial, involving direct neurotoxic effects of CO on brain chemistry, psychological trauma from the poisoning experience, and frustration with persistent cognitive and physical symptoms. Some patients develop irritability, emotional lability, or aggressive behavior. Personality changes ranging from subtle alterations in temperament to profound character change have been documented, particularly in cases involving basal ganglia damage. In the most severe cases, CO poisoning can cause psychosis with hallucinations, delusions, and disorganized thinking, though these acute psychiatric symptoms typically resolve with treatment of the underlying CO poisoning."
  ],
  effects: [
    "Short-term memory loss — difficulty forming and recalling recent memories",
    "Long-term memory impairment — difficulty recalling past events and learned information",
    "Impaired attention and concentration — difficulty focusing, easy distractibility",
    "Executive dysfunction — problems with planning, organizing, and decision-making",
    "Depression — persistent low mood, anhedonia, hopelessness",
    "Anxiety — excessive worry, panic attacks, generalized anxiety",
    "Personality changes — irritability, emotional lability, apathy, aggression",
    "Psychosis — hallucinations, delusions, disorganized thinking (in severe cases)",
    "Delirium — acute confusional state with fluctuating consciousness",
    "Loss of consciousness — ranging from brief syncope to prolonged coma",
    "Persistent cognitive deficits — chronic 'brain fog' and mental slowing",
    "Movement disorders — parkinsonism, gait disturbances, tremor"
  ]
}

export const longTermContent = {
  paragraphs: [
    "The long-term consequences of carbon monoxide poisoning represent one of the most clinically challenging aspects of this condition. While many patients recover fully with prompt and appropriate treatment, a significant proportion experience persistent or delayed neurological symptoms that can profoundly affect their quality of life, ability to work, and independence. The most important long-term complication is Delayed Neurological Syndrome (DNS), first described in detail by Haldane in 1902, which involves the recurrence or new onset of neurological symptoms days to weeks after apparent recovery from acute CO poisoning.",
    "DNS typically develops 2 to 40 days after the initial exposure and apparent recovery. The syndrome affects approximately 10-30% of patients who experience severe CO poisoning (typically defined as COHb >25% or loss of consciousness). The hallmark features include cognitive impairment (memory loss, executive dysfunction, mental slowing), neuropsychiatric symptoms (depression, anxiety, personality changes, psychosis), parkinsonian features (rigidity, tremor, bradykinesia, gait disturbance), and in severe cases, a progressive dementia-like syndrome. MRI imaging often reveals characteristic changes including white matter hyperintensities and lesions in the globus pallidus and other deep gray matter structures.",
    "The mechanism of DNS is not fully understood but is believed to involve a combination of delayed inflammatory responses, ongoing oxidative stress, reperfusion injury following oxygen treatment, and apoptotic cell death in vulnerable brain regions. The initial CO binding and subsequent hypoxia trigger a cascade of biochemical events including lipid peroxidation, neutrophil sequestration in the brain, and activation of microglia. These processes continue for days to weeks after CO elimination, potentially explaining the delayed onset of symptoms.",
    "Recovery from CO poisoning varies widely depending on the severity of exposure, the patient's age and pre-existing health status, the timeliness and adequacy of treatment, and individual susceptibility factors. Many patients with mild-to-moderate poisoning recover fully within days to weeks. Patients with severe poisoning may show gradual improvement over months, with the greatest recovery occurring in the first 3-6 months. Some patients, however, experience permanent neurological deficits. Rehabilitation including cognitive rehabilitation therapy, physical therapy, occupational therapy, and psychological support plays a crucial role in maximizing recovery potential."
  ],
  timeline: [
    { phase: "Acute Phase", timeframe: "0–24 hours", description: "Active CO exposure and immediate aftermath. Symptoms develop based on COHb levels. Emergency treatment with 100% oxygen or HBOT. Patients may appear to recover fully, but this recovery can be deceptive." },
    { phase: "Lag Phase", timeframe: "1–14 days", description: "A period of apparent normalcy or significant improvement. The patient may feel well and be discharged from medical care. However, invisible pathological processes (inflammation, oxidative stress, apoptosis) are continuing in the brain." },
    { phase: "DNS Onset", timeframe: "2–40 days", description: "Delayed Neurological Syndrome may develop with recurrence of symptoms: cognitive decline, personality changes, parkinsonian features, gait disturbances. This phase can be devastating as patients believed recovered suddenly deteriorate." },
    { phase: "Recovery Phase", timeframe: "1–6 months", description: "Gradual neurological recovery with the most significant improvements in the first 3 months. Cognitive rehabilitation, physical therapy, and occupational therapy are most effective during this period. Some symptoms persist." },
    { phase: "Long-Term", timeframe: "6+ months", description: "Plateau of recovery. Any remaining deficits are likely to be permanent, though gradual improvement may continue for up to 2 years. Ongoing support and monitoring are recommended." },
  ]
}

export const diagnosisContent = {
  methods: [
    { name: "Medical History", description: "A thorough history is the most important diagnostic tool. Key questions include: Were other people or pets in the household also affected? Do symptoms improve when leaving the building? Is there a source of combustion in the home? Were appliances recently serviced? Does the home have CO detectors?", limitations: "Patients may be unconscious or confused, limiting history-taking. Chronic exposure often has non-specific symptoms that mimic other conditions." },
    { name: "Physical Examination", description: "Physical findings in CO poisoning are non-specific. Tachycardia, tachypnea, hypertension, and fever may be present. Neurological examination may reveal confusion, ataxia, abnormal reflexes, or focal neurological deficits. Retinal exam may show flame-shaped hemorrhages. The classic cherry-red skin color is a post-mortem finding.", limitations: "No physical finding is specific to CO poisoning. Examination may be completely normal in mild cases or chronic exposure." },
    { name: "Pulse Oximetry", description: "Standard two-wavelength pulse oximeters measure the ratio of oxyhemoglobin to deoxyhemoglobin but cannot distinguish carboxyhemoglobin from oxyhemoglobin. Pulse oximetry readings may be falsely normal or only slightly decreased in CO poisoning.", limitations: "CRITICAL LIMITATION: Pulse oximetry is unreliable in CO poisoning. A patient with significant COHb levels may have a normal SpO2 reading. CO-oximetry is required for accurate assessment." },
    { name: "COHb Blood Test (CO-oximetry)", description: "The definitive diagnostic test for CO poisoning. Uses multi-wavelength spectrophotometry to directly measure carboxyhemoglobin levels. Normal non-smokers: 0-3%. Normal smokers: 3-10%. Symptomatic poisoning: >10%. Severe poisoning: >25-30%. COHb levels should be interpreted in context of the time elapsed since exposure ended.", limitations: "COHb levels decrease over time — levels measured hours after removal from exposure may not reflect peak levels. The clinical presentation should guide treatment regardless of COHb level." },
    { name: "Arterial Blood Gas (ABG)", description: "Measures PaO2, PaCO2, pH, bicarbonate, and lactate. In CO poisoning, PaO2 is typically normal (hypoxemia is not present because COHb does not affect dissolved oxygen). Metabolic acidosis (elevated lactate) may be present in severe poisoning. ABG does not measure COHb.", limitations: "ABG can be falsely reassuring because PaO2 is typically normal. ABG analyzers that do not perform CO-oximetry will miss the diagnosis entirely." },
    { name: "Neuroimaging (MRI/CT)", description: "CT may show bilateral low-density lesions in the globus pallidus and cerebral white matter in severe cases. MRI is more sensitive, showing T2 hyperintensity in the globus pallidus, white matter, and other structures. Diffusion-weighted imaging (DWI) can detect acute ischemic changes. MRI findings correlate with prognosis.", limitations: "Imaging may be normal in mild-to-moderate cases and early in the clinical course. Abnormalities may develop or progress over days to weeks. Normal imaging does not rule out significant CO poisoning." },
    { name: "Electrocardiogram (ECG)", description: "May show sinus tachycardia, ST-T wave changes, arrhythmias, or evidence of myocardial ischemia. Cardiac troponin should be measured in all patients with moderate-to-severe exposure, as myocardial injury is common and prognostically significant.", limitations: "ECG may be normal in mild cases. Cardiac biomarkers may not be elevated despite cardiac involvement." },
    { name: "Neuropsychological Testing", description: "Formal cognitive testing is important for documenting baseline function and tracking recovery. Tests assess memory, attention, executive function, processing speed, and visuospatial abilities. Testing should be performed in the acute phase and repeated at intervals to monitor recovery.", limitations: "Requires specialized personnel. Results may be confounded by patient effort, emotional state, and comorbid conditions. May not be available in all settings." },
  ]
}

export const treatmentContent = {
  steps: [
    { name: "Immediate Removal from Exposure", description: "The first and most critical step in treating CO poisoning is removing the patient from the source of CO exposure. If the patient is in an enclosed space with a suspected CO source, rescue personnel should ensure the area is ventilated before entering.", details: "Do not re-enter the contaminated area without appropriate respiratory protection. Call emergency services (911) immediately. Open windows and doors to ventilate the area if it can be done safely. Evacuate all occupants including pets. Do not assume that symptoms will resolve on their own — seek medical evaluation." },
    { name: "100% Oxygen via Non-Rebreather Mask", description: "High-flow 100% oxygen via a tight-fitting non-rebreather mask is the standard first-line treatment for CO poisoning. This reduces the half-life of COHb from approximately 4-6 hours (on room air) to approximately 60-90 minutes.", details: "A non-rebreather mask with a reservoir bag and one-way valves should be used at a flow rate of 10-15 L/min to ensure delivery of close to 100% oxygen. The oxygen should be continued until COHb levels are below 10% (below 5% in pregnant women) and all symptoms have resolved. Continuous cardiac monitoring should be established." },
    { name: "Hyperbaric Oxygen Therapy (HBOT)", description: "HBOT involves breathing 100% oxygen at pressures greater than atmospheric pressure (typically 2-3 ATA). This further reduces the COHb half-life to approximately 20-30 minutes and increases dissolved oxygen in plasma to levels that can sustain life even without hemoglobin.", details: "HBOT is recommended for patients with: COHb >25%, loss of consciousness, cardiac involvement (ischemia, arrhythmia, abnormal ECG), neurological symptoms, severe metabolic acidosis, pregnancy (lower threshold of COHb >15%), and symptoms persisting despite normobaric oxygen therapy. Typical treatment involves 1-3 sessions of 90-120 minutes each at 2.5-3.0 ATA. HBOT may reduce the incidence of delayed neurological syndrome." },
    { name: "Supportive Medical Care", description: "Comprehensive supportive care in a hospital setting includes continuous cardiac monitoring, intravenous fluids, treatment of arrhythmias, management of seizures, and monitoring for complications such as rhabdomyolysis and acute kidney injury.", details: "Patients with loss of consciousness, cardiac involvement, or persistent neurological symptoms should be admitted to an intensive care unit. Serial COHb measurements guide treatment duration. ECG and cardiac biomarkers (troponin) should be obtained. Liver and kidney function should be monitored. Seizures should be treated with benzodiazepines." },
    { name: "Follow-Up and Rehabilitation", description: "After acute treatment, patients require structured follow-up to monitor for delayed neurological syndrome and support recovery. This includes repeat neurological examinations, neuropsychological testing, and referral to rehabilitation services as needed.", details: "Follow-up should occur at 1, 4, and 12 weeks post-exposure at minimum. Any new or worsening neurological symptoms should prompt immediate re-evaluation. Cognitive rehabilitation, physical therapy, occupational therapy, and psychological support (counseling, support groups) should be provided as needed. Patients should be counseled about the signs and symptoms of DNS and instructed to seek immediate care if they occur." },
  ]
}